import keymirror from "keymirror";

const TYPES = keymirror({
  PROCESSING: null,
  AUTH_SUCCESS: null,
  AUTH_FAILURE: null,
  USER_LOGOUT: null,
  FETCHING_USER: null,
  USER_DATA: null,
  FETCH_USER_FAILURE: null,
  SUBMITTING_TICKET: null,
  SUBMIT_TICKET_SUCCESS: null,
  SUBMIT_TICKET_FAILURE: null,
  FETCHING_TICKETS: null,
  FETCH_REPORT_DATA: null,
  FETCH_AGENT_TICKETS: null,
  FETCH_TICKETS_FAILURE: null,
  FETCHING_TICKET: null,
  FETCH_TICKET_SUCCESS: null,
  FETCH_TICKET_FAILURE: null,
  FETCHING_AGENT: null,
  FETCH_AGENT_SUCCESS: null,
  FETCH_AGENT_FAILURE: null,
  CLOSING_TICKET: null,
  CLOSE_TICKET_SUCCESS: null,
  CLOSE_TICKET_FAILURE: null,
  SUBMITTING_COMMENT: null,
  SUBMIT_COMMENT_SUCCESS: null,
  SUBMIT_COMMENT_FAILURE: null,
});

export default TYPES;
